steps:
  - id: "docker-pull"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull ${_IMAGE_NAME}:latest || exit 0
    waitFor:
      - "-"

  - id: "docker-build"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil cp ${_ENV} .env && \
        docker build --cache-from ${_IMAGE_NAME}:latest -t ${_IMAGE_NAME}:${SHORT_SHA} -t ${_IMAGE_NAME}:latest .
    waitFor:
      - "docker-pull"

  - id: "docker-push"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker push ${_IMAGE_NAME}:${SHORT_SHA}
        docker push ${_IMAGE_NAME}:latest
    waitFor:
      - "docker-build"

  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        eval $(ssh-agent -s)
        echo "${_SSH_PRIVATE_KEY}" | tr -d "\r" | ssh-add -
        ssh -o StrictHostKeyChecking=no deployer@139.162.85.171 CLOUDSDK_PYTHON=/usr/bin/python 'docker-compose down'
        ssh -o StrictHostKeyChecking=no deployer@139.162.85.171 'if [ ! -z "$(docker images -q asia.gcr.io/kuantark-devops/cloud-build-hello-world:latest)" ]; then docker rmi asia.gcr.io/kuantark-devops/cloud-build-hello-world:latest; fi'
        ssh -o StrictHostKeyChecking=no deployer@139.162.85.171 CLOUDSDK_PYTHON=/usr/bin/python 'docker-compose up -d && docker-compose ps'
    waitFor:
      - "docker-push"

timeout: 500s
substitutions:
  _IMAGE_NAME: asia.gcr.io/${PROJECT_ID}/cloud-build-hello-world
  _ENV: gs://gludio/gludio-backend.env
