steps:
- name: 'alpine'
  args: [ 'echo', '${_DEV_ENV}' ]

- name: 'alpine'
  args: [ 'echo', '${_PROD_ENV}', '>>', '.env' ]

- name: 'alpine'
  args: [ 'ls', '-al' ]

#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'build', '-t' 'asia.gcr.io/$PROJECT_ID/cloud-build-hello-world', '.' ]
#
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'push', 'asia.gcr.io/$PROJECT_ID/cloud-build-hello-world' ]
