steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c', 'echo $_PROD_ENV && echo $_PROD_ENV > .env && ls -al && cat .env && date' ]
#    args: [ '-c', 'gcloud builds list > output.file && ls -al && cat output.file' ]
#      - 'ls -al && echo ${_PROD_ENV} && ls -al && which docker'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/cloud-build-hello-world:$TAG_NAME', '.' ]
#
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', 'asia.gcr.io/$PROJECT_ID/cloud-build-hello-world:$TAG_NAME' ]
