steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gsutil cp gs://gludio/gludio-backend.env .env && \
        docker build -t asia.gcr.io/$PROJECT_ID/cloud-build-hello-world .

images:
  - 'asia.gcr.io/$PROJECT_ID/cloud-build-hello-world'
