name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: git
      run: |
        which git;
        git tag -am "Tagging Services for release ${GITHUB_RUN_NUMBER}" v${GITHUB_RUN_NUMBER}
        git push origin v${GITHUB_RUN_NUMBER}
