name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -am "Tagging Services for release ${GITHUB_RUN_NUMBER}" v${GITHUB_RUN_NUMBER}
          git push origin v${GITHUB_RUN_NUMBER}
